<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>SCNET_Restart_Tool</RootNamespace>
    <AssemblyName>SCNET_Restart_Tool</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateManifests>true</GenerateManifests>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <ApplicationIcon>Res\ico.ico</ApplicationIcon>
    <StartupObject>SCNET_Restart_Tool.Program</StartupObject>
    <Deterministic>true</Deterministic>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Form\Settings\**" />
    <EmbeddedResource Remove="Form\Settings\**" />
    <None Remove="Form\Settings\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Form\Main\ToolMain.resx~RF13c1f3f.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Properties\app.manifest" />
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Res\ico.ico" />
    <None Include="Res\png\world_icon.png" />
    <None Include="Res\png\texture_icon.png" />
    <None Include="Res\png\skin_icon.png" />
    <None Include="Res\png\plugin_icon.png" />
    <None Include="Res\png\mod_icon.png" />
    <None Include="Res\png\log_icon.png" />
    <None Include="Res\png\config_icon.png" />
    <EmbeddedResource Include="Res\world_icon.ico" />
    <EmbeddedResource Include="Res\texture_icon.ico" />
    <EmbeddedResource Include="Res\skin_icon.ico" />
    <EmbeddedResource Include="Res\plugin_icon.ico" />
    <EmbeddedResource Include="Res\mod_icon.ico" />
    <EmbeddedResource Include="Res\log_icon.ico" />
    <EmbeddedResource Include="Res\config_icon.ico" />
    <EmbeddedResource Include="Res\ico.ico" />
  </ItemGroup>
</Project>